lifti_platform/lifti_platform/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

lifti_platform/users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('', views.dashboard, name='dashboard'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('finances/', views.finances, name='finances'),
    path('card-usage/', views.card_usage, name="card_usage"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', views.change_password, name='change_password'),
    path('initiate-payment/', views.initiate_payment, name='initiate_payment'),
    path('payze-webhook/', views.payze_webhook_gateway, name='payze_webhook_gateway'),
    path('payment-success/', views.success_redirect_gateway, name='payment_success'),
    path('payment-fail/', views.error_redirect_gateway, name='payment_fail'),
    path('generate-qr/', views.generate_qr, name='generate_qr'),
    path('cooperative/', views.cooperative, name='cooperative'),
    path('guest/', views.guest, name='guest'),
    path('send_sms/', views.send_recovery_sms, name='send_recovery_sms'),
    path('verify_code/', views.verify_code, name='verify_code'),
    path('update_password/', views.update_password, name='update_password')
]

lifti_platform/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from datetime import datetime
import requests

class MonthYearField(models.DateField):
    description = "A field to store only month and year"

    def get_prep_value(self, value):
        if value is not None:
            return value.replace(day=1)
        return value

    def from_db_value(self, value, expression, connection):
        return value

    def to_python(self, value):
        return value

class Cooperative(models.Model): 
    cooperative_name = models.CharField(max_length=50)
    cooperative_address = models.CharField(max_length=100)
    cooperative_device_price = models.DecimalField(max_digits=10, decimal_places=2, default=00.10)
    def __str__(self):
        return self.cooperative_name
    
class CooperativeExpense(models.Model):
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE, related_name='expenses')
    date = MonthYearField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.CharField(max_length=255)


class Client(AbstractUser):
    mobile_number = models.CharField(max_length=15)
    apartment_number = models.CharField(max_length=20)
    cooperative_id = models.CharField(max_length=50)
    password_changed = models.BooleanField(default=False)
    allowed_cooperatives = models.ManyToManyField(Cooperative, related_name='allowed_clients', blank=True)
    head = models.BooleanField(default=False)
    sms_sent = models.BooleanField(default=False)
    groups = models.ManyToManyField(
        'auth.Group',
        related_name='client_users',
        blank=True,
        help_text='The groups this client belongs to. A client will get all permissions granted to each of their groups.',
        verbose_name='groups',
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='client_users',
        blank=True,
        help_text='Specific permissions for this client.',
        verbose_name='user permissions',
    )
    def save(self, *args, **kwargs):
        if self.mobile_number and not self.sms_sent:
            # Logic to send SMS
            api_key = "9be3300ffa6688e040b6981d170d153b"  # Use your actual API key
            message = SmsText.objects.get(id=1).text
            sms_url = "https://sender.ge/api/send.php"
            params = {
                "apikey": api_key,
                "smsno": 2, 
                "destination": self.mobile_number,
                "content": message,
            }

            try:
                response = requests.get(sms_url, params=params)
                response.raise_for_status()
                self.sms_sent = True  # Mark SMS as sent
            except requests.RequestException as e:
                # Log error or handle exception
                print(e)

        super(Client, self).save(*args, **kwargs)

    def __str__(self):
        return self.username



class Card(models.Model): 
    card_number = models.CharField(max_length=20, unique=True)
    user = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='cards')
    temp = models.BooleanField(default=False)
    for_mobile = models.CharField(max_length=15, default='null')
    life_hours = models.CharField(max_length=15, default='null')
    created_at = models.DateTimeField(default=datetime.now)
    def __str__(self): 
        return self.card_number

class Device(models.Model): 
    device_name = models.CharField(max_length=50)
    device_ip = models.CharField(max_length=50)
    device_port = models.IntegerField()
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE)

class DeviceEvent(models.Model): 
    device_id = models.IntegerField()
    user = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='device_events', default=2)
    timestamp = models.CharField(max_length=250)
    pin = models.IntegerField()
    card = models.CharField(max_length=20)
    event_type = models.IntegerField()
    verify_mode = models.CharField
    processed = models.BooleanField(default=False)
    payed = models.CharField(max_length=20, default="0")

class Balance(models.Model):
    user_balance = models.DecimalField(max_digits=10, decimal_places=2)
    user = models.OneToOneField(Client, on_delete=models.CASCADE, related_name='balance')
    user_balance_delta = models.DecimalField(max_digits=10, decimal_places=2, default=0)

class SubscriptionType(models.Model): 
    subscription_name = models.CharField(max_length=50, default='აბონემენტი')
    subscription_days = models.IntegerField()
    subscription_price = models.DecimalField(max_digits=10, decimal_places=2)
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE, related_name='subscription_types')
    def __str__(self): 
        return self.subscription_name
    

class Subscription(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='subscriptions')
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    is_active = models.BooleanField(default=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=10)
    cooperative = models.ForeignKey(Cooperative, on_delete=models.CASCADE, related_name='subscriptions')

class SubsObserverLog(models.Model): 
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='subscription_logs')
    card_number = models.CharField(max_length=20)
    operation_to_do = models.CharField(max_length=50)
    processed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)


class BalanceObserverLog(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='balance_logs')
    card_number = models.CharField(max_length=20)
    operation_to_do = models.CharField(max_length=50)
    processed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

class CardObserverLog(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='card_logs')
    card_number = models.CharField(max_length=20)
    operation_to_do = models.CharField(max_length=50)
    processed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

class AllowedCoopObserver(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='allowed_cooperative_logs')
    cooperative = models.CharField(max_length=50)
    operation_to_do = models.CharField(max_length=50)
    processed = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

class Transaction(models.Model):
    user = models.ForeignKey(Client, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status_choices = [
        ('pending', 'Pending'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    status = models.CharField(max_length=20, choices=status_choices, default='pending')
    created_at = models.DateTimeField(auto_now_add=True)
    transaction_id = models.CharField(max_length=200, default="transaction")

class SmsText(models.Model):
    case = models.CharField(max_length=50)
    text = models.CharField(max_length=250)

lifti_platform/users/forms.py
from django import forms
from .models import CooperativeExpense, Cooperative, Client

class PasswordChangeForm(forms.Form):
    new_password = forms.CharField(label='New Password', widget=forms.PasswordInput)
    new_password_confirm = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        new_password = cleaned_data.get("new_password")
        new_password_confirm = cleaned_data.get("new_password_confirm")
        
        if new_password and new_password_confirm and new_password != new_password_confirm:
            raise forms.ValidationError("პაროლები არ ემთხვევა")
        
        return cleaned_data

    

class DateRangeForm(forms.Form):
    selected_month = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

class CooperativeExpenseForm(forms.ModelForm):
    class Meta:
        model = CooperativeExpense
        fields = ['date', 'amount', 'description']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

class ClientForm(forms.ModelForm):
    cooperative_id = forms.ModelChoiceField(queryset=Cooperative.objects.all(), label='Cooperative')

    class Meta:
        model = Client
        fields = '__all__'

    def clean_cooperative_id(self):
        cooperative = self.cleaned_data.get('cooperative_id')
        if cooperative:
            return cooperative.id
        return None

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.cooperative_id = self.cleaned_data['cooperative_id']
        if commit:
            instance.save()
        return instance

lifti_platform/users/templates/auth.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <!-- Link to Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="//cdn.web-fonts.ge/fonts/arial-geo/css/arial-geo.min.css">

    <!-- Link to jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body class="font-sans bg-gray-100" style="font-family: 'Arial GEO', sans-serif;">
    <main class="container mx-auto mt-8">
        {% block content %}
        {% endblock %}
    </main>

    <footer>
       
    </footer>
</body>
</html>

lifti_platform/users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Website{% endblock %}</title>
    <!-- Link to Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
    <link rel="stylesheet" href="//cdn.web-fonts.ge/fonts/bpg-glaho-web-caps/css/bpg-glaho-web-caps.min.css">

    <!-- Link to jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body class="font-sans bg-gray-100" style="font-family: 'BPG Glaho WEB Caps', sans-serif;">
    <!-- Header for desktop -->
    <header class="text-gray-600 body-font bg-gray-300 hidden md:block">
        <nav class="flex justify-between bg-white">
            <div class="px-5 xl:px-12 py-6 flex w-full items-center">
                <a class="text-3xl font-bold font-heading" href="/">
                  <img src="{% static 'logo.png' %}" width="100" />
                </a>
                <!-- Nav Links -->
                <ul class="hidden md:flex px-4 mx-auto font-semibold font-heading space-x-12">
                    <li><a class="{% if request.path == '/finances/' %}text-red-700{% endif %}" href="/finances">ფინანსები</a></li>
                    <li><a class="{% if request.path == '/card-usage/' %}text-red-700{% endif %}" href="/card-usage">ლოგები</a></li>
                    <li><a class="{% if request.path == '/cooperative/' %}text-red-700{% endif %}" href="/cooperative">ამხანაგობა</a></li>
                    <li><a class="{% if request.path == '/guest/' %}text-red-700{% endif %}" href="/guest">სტუმარი</a></li>
                    <li><a class="{% if request.path == '/dashboard/' %}text-red-700{% endif %}" href="/dashboard">მომხმარებლის სივრცე</a></li>
                </ul>
                <!-- Header Icons -->
                <div>
                    <form action="{% url 'logout' %}" method="post" class="">
                        {% csrf_token %}
                        <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                            გასვლა
                        </button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <!-- Header for mobile -->
    <header class="text-gray-600 body-font bg-gray-300 block md:hidden">
        <nav class="flex justify-between bg-white	">
            <div class="px-5 xl:px-12 py-6 flex w-full items-center flex justify-around">
                <a class="text-3xl font-bold font-heading" href="#">ლოგო</a>
                <!-- Hamburger Menu Icon -->
                <button id="menu-toggle" class="text-gray-500 focus:outline-none focus:text-gray-700">
                    <svg class="h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M3 18h18v-2H3v2zM3 11h18V9H3v2zm0-7h18V2H3v2z"/>
                    </svg>
                </button>
                <div>
                  <form action="{% url 'logout' %}" method="post" class="">
                      {% csrf_token %}
                      <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded">
                          გასვლა
                      </button>
                  </form>
              </div>
            </div>
        </nav>
    </header>

    <!-- Modal for mobile menu -->
    <div id="mobile-menu" class="fixed inset-0 bg-black bg-opacity-50 hidden">
        <div class="absolute top-0 right-0 p-4">
            <button id="close-menu" class="text-white focus:outline-none">
                <svg class="h-6 w-6 fill-current" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                    <path fill-rule="evenodd" d="M19.586 19.586a2 2 0 0 1-2.828 0L12 14.828l-4.95 4.95a2 2 0 0 1-2.828-2.828l4.95-4.95L4.222 7.95a2 2 0 1 1 2.828-2.828l4.95 4.95 4.95-4.95a2 2 0 1 1 2.828 2.828l-4.95 4.95 4.95 4.95z"/>
                </svg>
            </button>
        </div>
        <div class="flex justify-center items-center h-full">
            <ul class="text-white text-2xl text-center">
                <li><a class="{% if request.path == '/finances/' %}text-red-700{% endif %}" href="/finances">ფინანსები</a></li>
                <li><a class="{% if request.path == '/card-usage/' %}text-red-700{% endif %}" href="/card-usage">ლოგები</a></li>
                <li><a class="{% if request.path == '/cooperative/' %}text-red-700{% endif %}" href="/cooperative">ამხანაგობა</a></li>
                <li><a class="{% if request.path == '/guest/' %}text-red-700{% endif %}" href="/guest">სტუმარი</a></li>
                <li><a class="{% if request.path == '/dashboard/' %}text-red-700{% endif %}" href="/dashboard">მომხმარებლის სივრცე</a></li>
            </ul>
          </div>
    </div>

    <main class="container mx-auto mt-8">
        {% block content %}
        {% endblock %}
    </main>

    <footer>
       
    </footer>

    <script>
        $(document).ready(function(){
            $('#menu-toggle').click(function(){
                $('#mobile-menu').toggleClass('hidden');
            });

            $('#close-menu').click(function(){
                $('#mobile-menu').addClass('hidden');
            });
        });
    </script>
</body>
</html>

lifti_platform/users/templates/card_usage.html
{% extends 'base.html' %}

{% block title %}ლოგები{% endblock %}

{% block content %}
    <div class="container mx-auto p-4">
        <h2 class="text-2xl font-bold mb-4">ლოგები</h2>
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-300 shadow-md rounded">
                <thead>
                    <tr>
                        <th class="py-2 px-4 border-b">დრო</th>
                        <th class="py-2 px-4 border-b">მოწყობილობა</th>
                        <th class="py-2 px-4 border-b">ბარათი</th>
                        <th class="py-2 px-4 border-b">სტატუსი</th>
                        <th class="py-2 px-4 border-b">გადახდა</th>
                    </tr>
                </thead>
                <tbody>
                    {% for device_event in user_device_events %}
                        <tr>
                            <td class="py-2 px-4 border-b text-center">{{ device_event.timestamp }}</td>
                            <td class="py-2 px-4 border-b text-center">{{ device_event.device_id }}</td>
                            <td class="py-2 px-4 border-b text-center">{{ device_event.card }}</td>
                            <td class="py-2 px-4 border-b text-center font-bold {% if device_event.event_type == 0 %}text-green-600{% elif device_event.event_type == 27 %}text-red-600{% endif %}">
                                {% if device_event.event_type == 0 %}
                                    წარმატებული
                                {% elif device_event.event_type == 27 %}
                                    წარუმატებელი
                                {% else %}
                                    {{ device_event.event_type }}
                                {% endif %}
                            </td>
                            <td class="py-2 px-4 border-b text-center">{% if device_event.payed == "0" %}
                                    არასაკმარისი ბალანსი
                                {% elif device_event.payed == "sub" %}
                                    აბონემენტი
                                {% else %}
                                    გადახდა: {{ device_event.payed }}
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
        <!-- Pagination controls -->
<!-- Pagination controls -->
<div class="mt-4">
    {% if user_device_events.has_other_pages %}
        <ul class="flex justify-center">
            {% if user_device_events.has_previous %}
                <li class="mr-2">
                    <a href="?page=1" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold rounded-l">პირველი</a>
                </li>
                <li class="mr-2">
                    <a href="?page={{ user_device_events.previous_page_number }}" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold">უკან</a>
                </li>
            {% endif %}
            
            {% for num in user_device_events.paginator.page_range %}
                {% if num < 4 or num > user_device_events.paginator.num_pages|add:'-2' %}
                    <li class="mr-2">
                        <a href="?page={{ num }}" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold {% if num == user_device_events.number %}bg-gray-400{% endif %}">{{ num }}</a>
                    </li>
                {% elif num == 4 %}
                    <li class="mr-2">
                        <span class="px-4 py-2 bg-gray-200 text-gray-800 font-semibold">...</span>
                    </li>
                {% endif %}
            {% endfor %}
            
            {% if user_device_events.has_next %}
                <li class="mr-2">
                    <a href="?page={{ user_device_events.next_page_number }}" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold">შემდეგი</a>
                </li>
                <li>
                    <a href="?page={{ user_device_events.paginator.num_pages }}" class="px-4 py-2 bg-gray-200 hover:bg-gray-300 text-gray-800 font-semibold rounded-r">ბოლო</a>
                </li>
            {% endif %}
        </ul>
    {% endif %}
</div>


    </div>
{% endblock %}

lifti_platform/users/templates/change_password.html
{% extends 'base.html' %}

{% block title %}პაროლის შეცვლა{% endblock %}

{% block content %}
    <div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
        <h2 class="text-2xl font-bold mb-4">პაროლის შეცვლა</h2>
        <form method="post" class="space-y-4">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_new_password" class="block text-gray-700 text-sm font-bold mb-2">ახალი პაროლი:</label>
                <input type="password" name="new_password" id="id_new_password" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            <div class="mb-4">
                <label for="id_new_password_confirm" class="block text-gray-700 text-sm font-bold mb-2">გაიმეორე პაროლი:</label>
                <input type="password" name="new_password_confirm" id="id_new_password_confirm" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
            </div>
            {% if form.non_field_errors %}
                <div class="text-red-500">
                    {{ form.non_field_errors.as_ul }}
                </div>
            {% endif %}
            <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded">დამახსოვრება</button>
        </form>
    </div>
{% endblock %}

lifti_platform/users/templates/cooperative.html
{% extends 'base.html' %}

{% block title %}ამხანაგობა{% endblock %}

{% block content %}
<div class="md:max-w-4xl mx-auto">
    <div class="mx-auto">
            <div> 
                <span>ამხანაგობის ბალანსი:</span>
                <span>{{ cooperative_balance }}</span>
            </div>
            <!-- Tab Buttons -->
            <div class="bg-blue-500 p-2 rounded-t-lg">
                <div class="flex flex-wrap justify-center">
                    {% for data in tab_data %}
                    <button class="px-4 py-2 mb-2 mr-2 text-white font-semibold border-b-4 border-blue-700 hover:bg-blue-700 focus:outline-none tab-button" onclick="showTab('tab{{ forloop.counter }}')">{{ data.month }}</button>
                    {% endfor %}
                </div>
            </div>
        
            <!-- Tab Content -->
            {% for data in tab_data %}
            <div id="tab{{ forloop.counter }}" class="p-4 tab-content bg-white shadow-md rounded-lg {% if forloop.first %}block{% else %}hidden{% endif %}">
                <table class="table-auto border-collapse w-full">
                    <thead>
                        <tr>
                            <th class="px-4 py-2 bg-gray-200">თანხა</th>
                            <th class="px-4 py-2 bg-gray-200">აღწერა</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for expense in data.expenses %}
                        <tr>
                            <td class="border px-4 py-2">- {{ expense.amount }}</td>
                            <td class="border px-4 py-2">{{ expense.description }}</td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td class="border px-4 py-2" colspan="4">არჩეულ პერიოდში დანახარჯები არ მოიძებნა.</td>
                        </tr>
                        {% endfor %}
                        {% if data.total_expenses %}
                        <tr>
                            <td class="border px-4 py-2 bg-red-300" colspan="1">- {{ data.total_expenses }}</td>
                            <td class="border px-4 py-2" colspan="1">მთლიანი ხარჯი</td>
                        </tr>
                        {% endif %}
                        {% if data.total_amount %}
                        <tr>
                            <td class="border px-4 py-2 bg-green-500" colspan="1">+ {{ data.total_amount }}</td>
                            <td class="border px-4 py-2" colspan="1">შემოსავალი</td>
                        </tr>
                        {% endif %}
                        
                        {% if data.total_expenses %}
                        <tr>
                            <td class="border px-4 py-2" colspan="1">{{ data.net_total }}</td>
                            <td class="border px-4 py-2" colspan="1">ჯამი</td>
                        </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div>
            {% endfor %}

        {% if request.user.head %}
        <!-- Add New Cooperative Expense Form -->
        <h1 class="text-2xl font-bold mb-4 mt-10">ხარჯის დამატება</h1>
        <form method="post" class="mb-8">
            {% csrf_token %}
            <div class="mb-4">
                <label for="id_date" class="block text-gray-700 mb-1">თარიღი:</label>
                <input type="date" id="id_date" name="date" required class="w-full rounded border border-gray-300 py-2 px-3 focus:outline-none focus:border-blue-500">
            </div>
            <div class="mb-4">
                <label for="id_amount" class="block text-gray-700 mb-1">თანხა:</label>
                <input type="number" id="id_amount" name="amount" step="0.01" required class="w-full rounded border border-gray-300 py-2 px-3 focus:outline-none focus:border-blue-500">
            </div>
            <div class="mb-4">
                <label for="id_description" class="block text-gray-700 mb-1">აღწერა:</label>
                <input type="text" id="id_description" name="description" required class="w-full rounded border border-gray-300 py-2 px-3 focus:outline-none focus:border-blue-500">
            </div>
            <input type="hidden" id="id_cooperative" name="cooperative" value="{{ request.user.cooperative_id }}">
            <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">ხარჯის დამატება</button>
        </form>
        {% endif %}
        {% if messages %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                {% for message in messages %}
                    <span class="block sm:inline">{{ message }}</span>
                {% endfor %}
            </div>
        {% endif %}

    </div>
</div>
<style>
    .tab-button.active {
      background-color: #fff;
      border-color: #4299e1;
      color: #4299e1;
    }
  </style>
  
  <script>
    function showTab(tabId) {
      // Hide all tab content
      const tabContents = document.querySelectorAll('.tab-content');
      tabContents.forEach((content) => {
        content.classList.add('hidden');
      });
  
      // Show the selected tab content
      const selectedTab = document.getElementById(tabId);
      if (selectedTab) {
        selectedTab.classList.remove('hidden');
      }
  
      // Remove the 'active' class from all tab buttons
      const tabButtons = document.querySelectorAll('.tab-button');
      tabButtons.forEach((button) => {
        button.classList.remove('active');
      });
  
      // Add the 'active' class to the clicked tab button
      const clickedButton = document.querySelector(`[onclick="showTab('${tabId}')"]`);
      if (clickedButton) {
        clickedButton.classList.add('active');
      }
    }
  
    // Initialize the first tab
    showTab('tab6');
  </script>
{% endblock %}

lifti_platform/users/templates/guest.html
{% extends 'base.html' %}

{% block title %}სტუმრის დაშვება{% endblock %}

{% block content %}
<div class="max-w-md mx-auto mt-8 bg-white p-8 rounded shadow-md">
    <form action="{% url 'generate_qr' %}" method="post">
        {% csrf_token %}
        <div class="mb-4">
            <label for="for_mobile" class="block text-gray-700 font-bold mb-2">სტუმრის ტელეფონის ნომერი:</label>
            <input type="text" id="for_mobile" name="for_mobile" placeholder="ნომერი" class="border border-gray-300 rounded-md px-3 py-2 w-full">
        </div>
        <div class="mb-4">
            <label for="life_hours" class="block text-gray-700 font-bold mb-2">გაზიარების დრო (სთ):</label>
            <input type="text" id="life_hours" name="life_hours" placeholder="რამდენი საათი?" class="border border-gray-300 rounded-md px-3 py-2 w-full">
        </div>
        <button type="submit" class="bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded w-full">QR-ის გაგზავნა</button>
    </form>
    {% if message %}
        <div class="bg-green-100 border-l-4 border-green-500 text-green-700 p-4 mt-4" role="alert">
            <p>{{ message }}</p>
        </div>
    {% endif %}
</div>
{% endblock %}